---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: ec2instances.cloud.badmus.test
spec:
  group: cloud.badmus.test
  names:
    kind: EC2Instance
    listKind: EC2InstanceList
    plural: ec2instances
    singular: ec2instance
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: EC2Instance is the Schema for the ec2instances API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of EC2Instance
            properties:
              additionalStorage:
                items:
                  description: Storage defines the storage configuration for the EC2Instance.
                  properties:
                    deviceName:
                      type: string
                    encrypted:
                      type: boolean
                    volumeSize:
                      type: integer
                    volumeType:
                      type: string
                  required:
                  - deviceName
                  - encrypted
                  - volumeSize
                  - volumeType
                  type: object
                type: array
              amiId:
                description: foo is an example field of EC2Instance. Edit ec2instance_types.go
                  to remove/update
                type: string
              associatedPublicIP:
                type: boolean
              instanceType:
                type: string
              keyPair:
                type: string
              name:
                type: string
              region:
                type: string
              securityGroupIds:
                items:
                  type: string
                type: array
              storage:
                items:
                  description: Storage defines the storage configuration for the EC2Instance.
                  properties:
                    deviceName:
                      type: string
                    encrypted:
                      type: boolean
                    volumeSize:
                      type: integer
                    volumeType:
                      type: string
                  required:
                  - deviceName
                  - encrypted
                  - volumeSize
                  - volumeType
                  type: object
                type: array
              subnetId:
                type: string
              tags:
                additionalProperties:
                  type: string
                type: object
              userData:
                type: string
            required:
            - instanceType
            - region
            - storage
            type: object
          status:
            description: status defines the observed state of EC2Instance
            properties:
              instanceID:
                type: string
              phase:
                type: string
              publicIP:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
